http://localhost:61635/api/GetAllSmartDevices

###
http://localhost:61635/api/AddSmartDevice?type=Lodówka&name=Lod1&state=Chłodzi&localization=Kuchnia&disabled=false

###
http://localhost:61635/api/GetSingleSmartDevice?id=5cab1c91147378a8581099cf

###
http://localhost:61635/api/GetAllSmartDevicesWithSameName?name=Lod1

###
http://localhost:61635/api/GetAllSmartDevicesWithSameType?type=Lodówka

###
http://localhost:61635/api/GetAllSmartDevicesWithSameLocalization?localization=Kuchnia

###
http://localhost:61635/api/GetAllSmartDevicesWhichAreDisabled
###

http://localhost:61635/api/CheckIfSingleSmartDeviceIsDisabled?id=5cab1c91147378a8581099cf
###
http://localhost:61635/api/CheckIfSingleSmartDeviceIsDisabledAndSwitchOn?id=5cab1c91147378a8581099cf
####
http://localhost:61635/api/DeleteSmartDeviceFromCollection?id=5caa6502dd8c67339839ebab
###
http://localhost:61635/api/GetStateOfSingleSmartDevice?id=5cc76761dd8c634d442bc77a
###
http://localhost:61635/api/SetStateOfSingleSmartDevice?id=5cc76761dd8c634d442bc77a&state=Enabled
###
http://localhost:61635/api/SetTypeOfSingleSmartDevice?id=5cab1c91147378a8581099cf&type=Światło
###
http://localhost:61635/api/SetSpecificPropertyOfSingleSmartDevice?id=5cab1c91147378a8581099cf&propertyName=Name&propertyValue=TEST
###
POST http://localhost:61635/api/SetSpecificPropertyOfSingleSmartDevice?id=5cc76761dd8c634d442bc77a&propertyName=State&propertyValue=Enable
###
